name: linky
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  flutter_chat_bubble: ^2.0.2

  #Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.1.1
  firebase_database: ^11.0.2
  cloud_firestore: ^5.4.4
  intl: ^0.19.0
  shared_preferences: ^2.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
